//
//  Message.h
//  missingkids
//
//  Created by Gal Blank on 9/21/15.
//  Copyright © 2015 Gal Blank. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef enum{
    MESSAGEROUTE_INTERNAL,
    MESSAGEROUTE_API,
    MESSAGEROUTE_OTHER
}messageRoute;

typedef enum{
    MESSAGETYPE_SIGNIN = 0,
    MESSAGETYPE_SIGNIN_RESPONSE = 1,
    MESSAGETYPE_FETCH_PERSONS = 2,
    MESSAGETYPE_FETCH_PERSON_RESPONSE=3,
    MESSAGETYPE_HIDE_MENU_BUTTON = 1000,
    MESSAGETYPE_SHOW_MENU_BUTTON = 1001,
    MESSAGETYPE_CHANGE_MENU_BUTTON = 1002,
    MESSAGETYPE_SHOW_SHARING_MENU = 1003,
    MESSAGETYPE_SHARE_THIS_APP = 1004,
    MESSAGETYPE_SHOW_FILTER_OPTIONS = 1005,
    MESSAGETYPE_HIDE_FILTER_OPTIONS = 1006,
    MESSAGETYPE_SHOW_SORTING_OPTIONS = 1007,
    MESSAGETYPE_CONTACT_DEVELOPER = 1008,
    MESSAGETYPE_HIDE_MENU = 1009,
    MESSAGETYPE_SORT_BY_MISSINGDATE = 1010,
    MESSAGETYPE_SORT_BY_AGE = 1011,
    MESSAGETYPE_SORT_BY_SEX = 1012,
    MESSAGETYPE_FILTERBY_COUNTRY = 1013,
    MESSAGETYPE_SHOW_LIST_VIEW = 1014,
    MESSAGETYPE_APPLY_FILTER = 1015,
    MESSAGETYPE_CLEAR_FILTER = 1016,
    MESSAGETYPE_CALL_REGIONAL_AUTHORITIES = 1017,
    MESSAGETYPE_HIDE_CALLINGCARD = 1018,
    MESSAGETYPE_FETCH_GETREGIONALCONTACTS = 1019,
    MESSAGETYPE_FETCH_GETREGIONALCONTACTS_RESPONSE = 1020,
    MESSAGETYPE_UPDATE_LOCATION = 1021,
    MESSAGETYPE_GENERAL_SUCCESS = 10000,
    MESSAGETYPE_UPLOADIMAGE = 1022,
    MESSAGETYPE_SENDMESSAGE = 1023
}messageType;

typedef enum {
    FLOATINGBUTTON_TYPE_MENU = 1,
    FLOATINGBUTTON_TYPE_BACK
}FLOATINGBUTTONTYPE;


@interface Message : NSObject

@property(nonatomic)messageRoute mesRoute;
@property(nonatomic)messageType mesType;
@property(nonatomic,strong)id params;
@property(nonatomic)int ttl;

@end
